# Generated by Django 5.1.1 on 2025-09-05 22:42

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('author', models.CharField(max_length=120, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'permissions': [('can_view_books', 'Can view books')],
            },
        ),
    ]
